require "rake/testtask"
require 'find'


desc 'update git repository'
task :git do
  sh 'git add .'
  sh 'git commit -m "updates"'
  sh 'git push'
end

Rake::TestTask.new(:test) do |t|
  t.libs << "."
  t.libs << "."
  t.test_files = FileList['./*_test.rb']
end

desc 'do everything'
task :all => [:git, :list, :test]

desc 'list files'
task :list do
  Find.find(".") do |path|
    filename = path.gsub(/^\.\//, "")
    puts filename if filename[0] != "." && File.file?(path)
  end
end

# task :default => :test
