require "rake/testtask"

desc 'update git repository'
task :git do
  sh 'git add .'
  sh 'git commit -m "updates"'
  sh 'git push'
end

# desc 'Run tests'
# task :default => :test

Rake::TestTask.new(:test) do |t|
  t.libs << "."
  t.libs << "."
  t.test_files = FileList['./*_test.rb']
end