require "rake/testtask"

desc 'update git repository'
task :git do
  sh 'git add .'
  sh 'git commit -m "updates"'
  sh 'git push'
end

Rake::TestTask.new(:test) do |t|
  t.libs << "."
  t.libs << "."
  t.test_files = FileList['./*_test.rb']
end

desc 'do everything'
task :all => [:git, :test]

# task :default => :test
