source 'https://rubygems.org'

ruby '2.5.5'
gem 'sinatra', '1.4.7'
gem 'sinatra-contrib'
gem 'erubis', '2.7.0'
gem 'webrick', '1.4.2'

gem 'minitest', '5.10.3'
gem 'rack-test', '2.1.0'

gem 'pg', '1.5.3'